"""add hero table

Revision ID: b4521d3fa862
Revises: 638980d150b6
Create Date: 2026-07-15 21:40:42.331114

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4521d3fa862"
down_revision: Union[str, Sequence[str], None] = "638980d150b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # Якщо у тебе є індекси, додаємо і їх (необов'язково, якщо поля прості):
    op.create_index(op.f("ix_hero_name"), "hero", ["name"], unique=False)
    op.create_index(op.f("ix_hero_age"), "hero", ["age"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hero_age"), table_name="hero")
    op.drop_index(op.f("ix_hero_name"), table_name="hero")
    op.drop_table("hero")
    # ### end Alembic commands ###
