name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # 1. Етап тестування
  test:
    runs-on: ubuntu-latest
    
    # Виносимо змінні сюди — тепер вони доступні для КОЖНОГО кроку всередині цього джоба
    env:
      DATABASE_URL: sqlite:///./test.db
      SECRET_KEY: dummy_secret_key_for_github_actions_testing_purposes_only_123

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Тепер Alembic бачитиме SECRET_KEY і успішно виконає імпорт
    - name: Run Alembic Migrations
      run: alembic upgrade head

    # Pytest теж автоматично отримає ці змінні
    - name: Run pytest
      run: pytest

  # 2. Етап деплою
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}